config/routes.rb
Observer::Application.routes.draw do
  resources :connections

  resources :dashboards do
    match 'update-widgets' => 'dashboards#update_widgets', :as => :update_widgets, :constraints => {:format => /json/}
    match 'add-widget' => 'dashboards#add_widget', :as => :add_widget, :via => :post
    match 'new-widget' => 'dashboards#new_widget', :as => :new_widget
    match 'remove-widget' => 'dashboards#remove_widget', :as => :remove_widget, :constraints => {:format => /json/}

    collection do
      match 'view/:token' => 'dashboards#view', :as => :view
      match 'view/:token/widgets/:dashboard_widget_id' => 'dashboards#widget', :as => :widget
    end
  end

  resources :widgets do
    collection do
      match 'tag/:tag' => 'widgets#show_tag', :as => :show_tag
      match 'preview', :as => :preview
      match 'copy/:id' => 'widgets#copy', :as => :copy
    end
  end

  resources :queries do
    collection do
      post 'run'
      match 'data/:token' => 'queries#data', :constraints => {:format => /(html)/}, :as => :data
      match 'copy/:id' => 'queries#copy', :as => :copy
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  match 'ajax-proxy' => 'website#ajax'

  root :to => 'website#index'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  attr_accessible :meta, :css, :html, :js, :name, :column, :row, :user_id, :data
  validates :name, :presence => true
  has_paper_trail :only => [:css, :html, :js]
  belongs_to :user
  has_many :dashboards, :through => :dashboards_widgets
  has_many :widget_tags

  def parsed_js(params = {})
    self.parse(self.js, params)
  end

  def parsed_css(params = {})
    self.parse(self.css, params)
  end

  def parsed_html(params = {})
    self.parse(self.html, params)
  end

  def parse(content, params)
    LiquidTemplate.for_widget.parse(content).render params
  end

  def last_tag
    self.widget_tags.last
  end

  def find_tag(name)
    self.widget_tags.find_by_name(name)
  end

  def add_tag(name, desc)
    tag = WidgetTag.new
    tag.name = name
    tag.desc = desc
    tag.widget = self
    tag.version_id = self.versions.last.id
    tag.save
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @widgets }
    end
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
    @widget.user = current_user
    @widget.column ||= 4
    @widget.row ||= 2
    @widget.name = 'untitled'
    @widget.save
    redirect_to(
      edit_widget_path(@widget.id, :redirect => params[:redirect])
    )
  end

  # GET /widgets/copy/1
  def copy
    @widget = Widget.find(params[:id])
    attributes = @widget.attributes
    attributes.delete('id')
    attributes.delete('created_at')
    attributes.delete('updated_at')

    widget = Widget.new
    widget.attributes = attributes
    widget.name = "#{widget.name} (1)"
    widget.save

    redirect_to(
      edit_widget_path(widget.id, :redirect => params[:redirect])
    )
  end

  # GET /widgets/1/edit
  def edit
    @widget = Widget.find(params[:id])
    @queries = Query.all
    @redirect = param(:redirect, widgets_path)
  end

  # PUT /widgets/1
  def update
    @widget = Widget.find(params[:id])

    respond_to do |format|
      if @widget.update_attributes(params[:widget])
        format.json { head :no_content }
      else
        flash[:errors] = @widget.errors
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy

    respond_to do |format|
      format.html { redirect_to widgets_url }
      format.json { head :no_content }
    end
  end

  # POST /widgets/preview
  def preview
    @widget = params[:widget].nil? ? {} : params[:widget]

    begin
      data = JSON.parse(@widget[:data])
    rescue
      data = {}
    end
    @widget[:js] = LiquidTemplate.for_widget.parse(@widget[:js]).render data
    render :layout => 'basic'
  end

  # GET /widgets/1
  def show
    @widget = Widget.find(params[:id])
    render :layout => 'basic'
  end

  # GET /widgets/1/tag/0.0.1
  def show_tag
    widget = Widget.find(params[:id])
    @widget = widget.find_tag(params[:tag]).version.reify

    render :layout => 'basic'
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
  def js_filter(js)
    js.gsub(/\{\{.+\}\}/) { |match|
      data_queries_path :token => match[2, match.length - 4]
    }
  end

  def widget_css(widget)
    sandbox_css("widget-#{widget.id}", widget.css)
  end

  def sandbox_css(cls, css)
    mixins = <<eos
  @mixin defaultHeadings($color) {
    h1, h2 {
      color: $color;
      margin: 0 0 5px;
      padding: 0;
    }

    h1 {
      font-size: 18px;
    }

    h2 {
      font-size: 14px;
    }
  }

  @mixin white($mode:border) {
    padding: 10px;
    font-size: 14px;
    color: grey;
    @include defaultHeadings(grey);

    @if $mode == transparent {
      background: none;
    } @else {
      background-color: #fff;

      @if $mode != no-border {
        border: 10px solid #eee;
      }
    }
  }

  @mixin solarized {
    font-size: 14px;
    background-color: #042029;
    color: #839496;
    padding: 10px;
    @include defaultHeadings(#B58900);

    a {
      color: #268BD2;
    }
  }

  @mixin dark_grey($mode:border) {
    font-size: 14px;
    color: #ddd;
    padding: 10px;
    @include defaultHeadings(#fff);

    @if $mode == transparent {
      background: none;
    } @else {
      background-color: grey;

      @if $mode != no-border {
        border: 10px solid #ccc;
      }
    }
  }
eos
    begin
      engine = Sass::Engine.new("#{mixins} .#{cls} { #{css} }", :syntax => :scss)
      "<style>#{engine.render}</style>"
    rescue
      ""
    end
  end

  def options_value(widget, name, default)
    if widget.options.nil? || widget.options[name].nil?
      return default
    end
    widget.options[name]
  end

  def widget_modifier(data)
    remove_btn = ''

    if !data[:remove].nil?
      remove_btn = '<div class="dashboard-widget-remove" data-remove><i class="icon-cross"></i></div>'
    end
<<eos
  <div class="widget-modifier-group" data-widget-modifier>
  #{remove_btn}
  </div>
eos
  end

  def widget_sandbox(src = '', id = '', widget_id = '', widget_class = '')
<<eos
<iframe
  id="#{id}"
  name="#{id}"
  class="widget-sandbox #{widget_class}"
  seemless="seemless"
  src="#{src}"
  scrolling="no"
  data-widget-id="#{widget_id}"
  data-sandbox
  data-dimensions="#{Settings.gridster.dimensions}"></iframe>
eos
  end
end

app/views/widgets/_builder.ejs.erb
<%= form_tag({
  :class => 'form--dark-panel',
  'data-content' => true
}) do %>
  <div data-bind="foreach: meta">
    <!-- ko ifnot: isArray -->
      <div data-bind="template: 'builder-input', data: $data"></div>
    <!-- /ko -->
    <!-- ko if: isArray -->
      <div data-bind="template: 'builder-array', data: $data"></div>
    <!-- /ko -->
  </div>
<% end %>

<script type="text/html" id="builder-input">
  <label>
    <!-- ko if: label -->
      <div data-bind="text: label"></div>
    <!-- /ko -->

    <input data-bind="attr: {
      'type': type,
      'name': name,
      'placeholder': placeholder,
      'data-auto-save': autoSave,
      'data-list': forList,
    },
    value: value"/>
  </label>
</script>
<script type="text/html" id="builder-array-data">
  <div class="row">
    <div class="small-12 columns">
      <div data-bind="foreach: value">
        <div class="widget-builder__data">
          <div data-bind="foreach: $parent.schema">
            <div class="widget-builder__data__schema">
              <span class="widget-builder__data__schema__name" data-bind="text: label"></span>:
              <span data-bind="text: $parent[name]"></span>
            </div>
          </div>
          <i
            class="icon-cross widget-builder__delete-icon"
            data-delete
            data-bind="attr: {
              'data-index': $index,
              'data-list-name': $parent.name
            }"
          ></i>
        </div>
      </div>
    </div>
  </div>
</script>
<script type="text/html" id="builder-array">
  <div class="row">
    <div class="large-12 columns">
      <label class="widget-builder__array-label" data-bind="text: label">
      </label>
      <div
        class="widget-builder__list"
        data-list-form
        data-bind="attr: {
          'data-name': name
        }"
      >
        <div data-bind="template: 'builder-array-data', data: $data"></div>
        <div data-bind="foreach: schema">
          <div data-bind="template: 'builder-input', data: $data"></div>
        </div>
        <div class="clearfix">
          <button
            class="button small secondary right disabled"
            type="button"
            data-add-item
          >Add</button>
        </div>
      </div>
    </div>
  </div>
</script>

app/views/widgets/_builder.html.erb
<div data-content>
  <div data-bind="foreach: meta">
    <!-- ko ifnot: isArray -->
      <div data-bind="template: 'builder-input', data: $data"></div>
    <!-- /ko -->
    <!-- ko if: isArray -->
      <div data-bind="template: 'builder-array', data: $data"></div>
    <!-- /ko -->
  </div>
</div>

<script type="text/html" id="builder-input">
  <label>
    <!-- ko if: label -->
      <div data-bind="text: label"></div>
    <!-- /ko -->

    <input data-bind="attr: {
      'type': type,
      'name': name,
      'data-auto-save': autoSave,
      'placeholder': placeholder,
      'data-list': forList
    },
    value: value
    "/>
  </label>
</script>
<script type="text/html" id="builder-array-data">
  <div class="row">
    <div class="small-12 columns">
      <div data-bind="foreach: value">
        <div class="widget-builder__data">
          <div data-bind="foreach: $parent.schema">
            <div class="widget-builder__data__schema">
              <span class="widget-builder__data__schema__name" data-bind="text: label"></span>:
              <span data-bind="text: $parent[name]"></span>
            </div>
          </div>
          <i
            class="icon-cross widget-builder__delete-icon"
            data-delete
            data-bind="attr: {
              'data-index': $index,
              'data-list-name': $parent.name
            }"
          ></i>
        </div>
      </div>
    </div>
  </div>
</script>
<script type="text/html" id="builder-array">
  <div class="row">
    <div class="large-12 columns">
      <label class="widget-builder__array-label" data-bind="text: label">
      </label>
      <div
        class="widget-builder__list"
        data-list-form
        data-bind="attr: {
          'data-name': name
        }"
      >
        <div data-bind="template: 'builder-array-data', data: $data"></div>
        <div data-bind="foreach: schema">
          <div data-bind="template: 'builder-input', data: $data"></div>
        </div>
        <div class="clearfix">
          <button
            class="button small secondary right disabled"
            type="button"
            data-add-item
          >Add</button>
        </div>
      </div>
    </div>
  </div>
</script>

app/views/widgets/_preferences_modal.html.erb
<div class="widget-preferences-group reveal-modal" id="widget-preferences" data-url="<%= widget_path %>" data-widget-preferences data-reveal>
  <div class="reveal-modal__title"><i class="icon-cog"></i> Preferences</div>
  <div class="reveal-modal__content">
  <%= form_for(@widget, html: { id: 'modal_edit_widget' } ) do |f| %>
    <%= f.hidden_field :column, { 'data-field' => true } %>
    <%= f.hidden_field :row, { 'data-field' => true } %>
    <%= overlay_spinner.html_safe %>
    <div class="widget-size-options-group" data-size-options data-value="[<%= @widget.column %>, <%= @widget.row %>]">
      <label>Select a size</label>
      <% 1.upto(Settings.gridster.max_size[1]) do |row| %>
      <div class="widget-size-options-row">
        <% 1.upto(Settings.gridster.max_size[0]) do |column| %>
        <div
          class="widget-size-option widget-size-option-col"
          data-option
          data-col="<%= column %>"
          data-row="<%= row %>"
        ></div>
        <% end %>
      </div>
      <% end %>
    </div>
    <div>
      <a href="<%= widget_path @widget %>" target="_blank">Preview</a>
    </div>
    <button class="button secondary" tabindex="2" data-cancel type="button"><i class="icon-back"></i>Cancel</button>
    <button class="button" type="submit" tabindex="3" data-save><i class="icon-save"></i>OK</button>
  </div>
  <% end %>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/widgets/_previewer.html.erb
<div
  class="widget-previewer"
  data-widget-previewer
  <% if defined? widget %>
    data-auto-play="1"
  <% end %>
>
  <div class="widget-previewer__content">
    <%= overlay_spinner.html_safe %>
    <%= widget_sandbox('', 'widget-sandbox', '', 'interactive').html_safe %>
    <div class="widget-debugger-group" data-widget-debugger>
      <pre class="widget-debugger__console" data-console></pre>
      <div class="widget-debugger__tip">Check your JS console for more details. </div>
    </div>
    <%= form_tag preview_widgets_path, :target => 'widget-sandbox', 'data-widget-preview-form' => true do %>
      <%= hidden_field_tag 'widget[js]', (defined? widget) ? widget.js : '' %>
      <%= hidden_field_tag 'widget[css]', (defined? widget) ? widget.css : '' %>
      <%= hidden_field_tag 'widget[html]', (defined? widget) ? widget.html : '' %>
      <%= hidden_field_tag 'widget[data]', (defined? widget) ? widget.data : '' %>
      <%= hidden_field_tag 'widget[row]', (defined? widget) ? widget.row : '' %>
      <%= hidden_field_tag 'widget[column]', (defined? widget) ? widget.column : '' %>
    <% end %>
  </div>
</div>

app/views/widgets/_resources_modal.html.erb
<div class="widget-resources-group reveal-modal" id="widget-resources" data-reveal>
  <div class="reveal-modal__title">
    <a href="<%= queries_path %>"><i class="icon-database"></i> Resources</a>
  </div>
  <div class="reveal-modal__content">
    <div class="widget-resources__items">
      <% if !@queries.nil? %>
        <% @queries.each do |q| %>
        <div class="widget-resources__item">
          <div data-copy-token data-clipboard-text="<%= q.token %>" class="widget-resources__copy-token">
            <div class="widget-resources__query-name"><%= q.name %></div>
            <div class="widget-resources__query-token"><%= q.token %></div>
          </div>
          <a href="<%= edit_query_path(q, :redirect => request.fullpath) %>" title="edit this data" class="widget-resources__query-edit"><i class="icon-pencil" data-edit></i></a>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="widget-resources__actions">
      <a href="#" class="button secondary small" data-cancel><i class="icon-back"></i> Cancel</a>
      <a href="<%= new_query_path(:redirect => request.fullpath) %>" title="new data" class="button small widget-resources__action"><i class="icon-plus"></i> New</a>
    </div>
  </div>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/widgets/_widget.html.erb
<%= sandbox_css('widget-group', css).html_safe %>
<div class="widget-group" data-widget-sandbox>
  <%= html_safe html %>
</div>
<% content_for :javascript do %>
<script type="text/javascript">
(function($, Observer, window, undefined) {
  var modules = Observer.modules;
  var helpers = Observer.helpers;

  $(function() {
    var widget = modules.widget($('[data-widget-sandbox]'), {
      autoRefresh: $('.show.widgets').length
    });

    try {
      $.proxy(function(modules, ko, undefined) {
        var
          document = undefined,
          window = undefined
          ;
        <% if js.present? %>
          <%= html_safe js %>
        <% end %>
      }, widget)(Observer.modules, ko);
    } catch (e) {
      console.log(e);
      window.parent.Observer.trigger('log', e.stack);
    }
  });
}(jQuery, Observer, window));
</script>
<% end %>

app/views/widgets/edit.html.erb
<% content_for :tools do %>
<ul class="right dashboard-tools">
  <li class="divider"></li>
  <li>
    <a href="#" title="add resources" data-widget-resources data-modal-id="widget-resources">
      <i class="icon-database dashboard-tools-icon"></i> Resources
    </a>
  </li>
  <li class="divider"></li>
  <li>
    <a href="#" title="Preferences" data-reveal-id="widget-preferences" data-reveal>
      <i class="icon-cog dashboard-tools-icon"></i> Preferences
    </a>
  </li>
  <li class="divider"></li>
  <li><a href="<%= copy_widgets_path @widget, :redirect => @redirect %>" data-confirm="Save this as a new widget?"><i class="icon-docs"></i> Save as </a></li>
  <li class="divider"></li>
  <li><a href="<%= @redirect %>"><i class="icon-forward"></i> Done</a></li>
</ul>
<% end %>
<div
  class="widget-name editable-name"
  data-editable-name
  data-url="<%= widget_path %>"
  data-name="widget[name]"
  contenteditable="true"
><%= @widget.name %></div>
<%= render 'previewer', :widget => @widget %>
<%= form_for(@widget, :html => { :class => 'widget-form', 'data-widget-form' => true }) do |f| %>
<div class="row">
  <div class="large-12 columns" id="widget-editor-layout" data-widget-editor-layout>
    <div class="large-6 columns" data-editor-group="left">
      <div data-tabs>
        <dl class="tabs" data-flight-tabs>
          <dd class="active" data-target="js"><a href="#">JS</a></dd>
          <dd data-target="meta"><a href="#">Meta</a></dd>
        </dl>
        <div class="tabs-content">
          <div class="content active" data-id="js">
            <%= f.hidden_field :js %>
            <%= render '/editor',
              :mode => 'js',
              :url => widget_path,
              :prefix => 'widget',
              :auto_preview => true
            %>
          </div>
          <div class="content" data-id="meta">
            <%= f.hidden_field :meta, "data-meta-field" => true %>
            <%= render '/editor',
              :mode => 'yaml',
              :url => widget_path,
              :prefix => 'widget',
              :bind => '[data-meta-field]',
              :auto_preview => false
            %>
          </div>
        </div>
      </div>
    </div>
    <div class="large-6 columns" data-editor-group="right">
      <div data-tabs>
        <dl class="tabs">
          <dd class="active" data-target="html"><a href="#">HTML</a></dd>
          <dd data-target="css"><a href="#">CSS</a></dd>
          <dd data-target="builder"><a href="#">Widget builder</a></dd>
        </dl>
        <div class="tabs-content">
          <div class="content active" data-id="html">
            <%= f.hidden_field :html, :placeholder => 'html' %>
            <%= render '/editor',
              :mode => 'html',
              :url => widget_path,
              :prefix => 'widget',
              :auto_preview => true
            %>
          </div>
          <div class="content" data-id="css">
            <%= f.hidden_field :css, :placeholder => 'css' %>
            <%= render '/editor',
              :mode => 'css',
              :url => widget_path,
              :prefix => 'widget',
              :auto_preview => true
            %>
          </div>
          <div class="content" data-id="builder">
            <div
              class="widget-builder-group"
              data-widget-builder
              data-meta="<%= @widget.meta %>"
              data-save-url="<%= widget_path %>"
              data-auto-save= "true"
            >
              <%= f.hidden_field :data, { "data-value" => true } %>
              <%= render 'builder' %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<% end %>
<%= render 'preferences_modal' %>
<%= render 'resources_modal' %>

app/views/widgets/index.html.erb
<div class="row">
  <div class="large-2 columns">
  </div>
  <div class="large-8 columns large-centered">
    <h1>Widgets</h1>
    <table class="table--common">
      <thead>
        <tr>
          <th>Name</th>
          <th>Created by</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
    <% @widgets.each do |widget| %>
        <tr>
          <td><a href="<%= edit_widget_path(widget) %>"><%= widget.name %></a></td>
          <td>
          <%= widget.user.username %>
          </td>
          <td class="action-cell">
              <a href="<%= edit_widget_path(widget) %>" class="action"><i class="icon-pencil"></i></a>
          </td>
          <td class="action-cell">
            <a href="<%= widget_path(widget) %>" class="action" data-confirm="Are you sure?" data-method="delete">
              <i class="icon-cross"></i>
            </a>
          </td>    </tr>
    <% end %>
      </tbody>
    </table>

    <br />

    <a href="<%= new_widget_path %>" class="button small"><i class="icon-plus"></i>New widget</a>
  </div>
  <div class="large-2 columns">
  </div>
</div>

app/views/widgets/preview.html.erb
<%= render 'widget', {
  :css => @widget[:css],
  :html => @widget[:html],
  :js => @widget[:js]
} %>

app/views/widgets/show.html.erb
<%= render 'widget', {
  :css => @widget.css,
  :html => @widget.html,
  :js => @widget.js_parsed
} %>

app/views/widgets/show_tag.html.erb
<%= render 'widget', {
  :css => @widget.parsed_css,
  :html => @widget.parsed_html,
  :js => @widget.parsed_js
} %>