config/routes.rb
Observer::Application.routes.draw do
  resources :connections

  resources :dashboards do
    match 'update-widgets' => 'dashboards#update_widgets', :as => :update_widgets, :constraints => {:format => /json/}
    match 'add-widget' => 'dashboards#add_widget', :as => :add_widget, :via => :post
    match 'new-widget' => 'dashboards#new_widget', :as => :new_widget
    match 'remove-widget' => 'dashboards#remove_widget', :as => :remove_widget, :constraints => {:format => /json/}

    collection do
      match 'view/:token' => 'dashboards#view', :as => :view
      match 'view/:token/widgets/:dashboard_widget_id' => 'dashboards#widget', :as => :widget
    end
  end

  resources :widgets do
    collection do
      match 'tag/:tag' => 'widgets#show_tag', :as => :show_tag
      match 'preview', :as => :preview
      match 'copy/:id' => 'widgets#copy', :as => :copy
    end
  end

  resources :queries do
    collection do
      post 'run'
      match 'data/:token' => 'queries#data', :constraints => {:format => /(html)/}, :as => :data
      match 'copy/:id' => 'queries#copy', :as => :copy
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  match 'ajax-proxy' => 'website#ajax'

  root :to => 'website#index'

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  attr_accessible :data, :is_public, :name, :scale, :user_id, :width, :height, :token
  validates :name, :presence => true
  validates :user_id, :presence => true

  belongs_to :user
  has_many :widgets, :through => :dashboards_widgets

  before_create :before_create
  def before_create
    if (self.token.nil?)
      self.token = loop do
        random_secret = SecureRandom.urlsafe_base64(6, false).downcase
        break random_secret unless self.class.exists?(token: random_secret)
      end
    end
  end

  def update_widgets(widgets)
    self.transaction do
      widgets.each do | widget |
        dw = self.dashboard_widgets.where('id = ?', widget['id']).first

        if !dw.nil?
          dw.col = widget['col']
          dw.row = widget['row']
          dw.size_x = widget['size_x']
          dw.size_y = widget['size_y']
          dw.save
        end
      end
    end
  end

  def add_widget_from_data(widget)
    widget['dashboard_id'] = self.id
    widget[:size_x] = widget[:column]
    widget[:size_y] = widget[:row]
    widget[:col] = 1
    widget[:row] = 1

    self.dashboard_widgets.each do |w|
      widget[:row] = [w.col, widget[:row]].max
    end

    @last_dashboard_widget = DashboardsWidgets.create_from_data(widget)
    @last_dashboard_widget.save
  end

  def last_dashboard_widget
    @last_dashboard_widget
  end

  def remove_widget(id)
    dw = DashboardsWidgets.find(id)

    if dw.dashboard_id == self.id
      dw.destroy
    else
      false
    end
  end

  def dashboard_widgets
    DashboardsWidgets.includes(:widget).where("dashboard_id = ?", self.id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate_user!, :except => [:view]

  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all(:include => :user)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dashboards }
    end
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
    @dashboard.user = current_user
    @dashboard.name = 'untitled'
    @dashboard.save
    redirect_to(edit_dashboard_path(@dashboard))
  end

  # GET /dashboards/1/edit
  def edit
    @dashboard = Dashboard.find(params[:id])
    @dashboard_widgets = @dashboard.dashboard_widgets
    @widgets = Widget.all(:include => :user)
  end

  # PUT /dashboards/1
  def update
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      if @dashboard.update_attributes(params[:dashboard])
        format.json { head :no_content }
      else
        flash[:errors] = @dashboard.errors
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /dashboards/view/TOKEN
  def view
    @dashboard = Dashboard.find_by_token(params[:token])
    @dashboard_widgets = @dashboard.dashboard_widgets
  end

  # PUT /dashboards/1/update-widgets
  # PUT /dashboards/1/update-widgets.json
  def update_widgets
    @dashboard = Dashboard.find(params[:dashboard_id])
    widgets = ActiveSupport::JSON.decode(params[:widgets])
    respond_to do |format|
      if @dashboard.update_widgets(widgets)
        format.json { head :no_content }
      else
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /dashboards/:token/widgets/:dashboard_widget_id
  def widget
    @dashboard = Dashboard.find_by_token(params[:token])
    print params[:dashboard_widget_id]
    @widget = @dashboard.dashboard_widgets.find(params[:dashboard_widget_id])
    render :layout => 'basic'
  end

  # GET /dashboards/1/new-widget
  def new_widget
    @dashboard = Dashboard.find(params[:dashboard_id])
    @widgets = Widget.all(:include => :user)
  end

  # POST /dashboards/1/add-widget
  def add_widget
    @dashboard = Dashboard.find(params[:dashboard_id])
    @dashboard.add_widget_from_data(params[:widget])
    redirect_to(edit_dashboard_path(@dashboard))
  end

  # DELETE /dashboards/1/remove-widgets.json
  def remove_widget
    @dashboard = Dashboard.find(params[:dashboard_id])
    respond_to do |format|
      if @dashboard.remove_widget(params[:id])
        format.json { head :no_content }
      else
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy

    respond_to do |format|
      format.html { redirect_to dashboards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def dashboard_settings
    Settings.dashboard
  end
end

app/views/dashboards/_preferences_modal.html.erb
<div class="dashboard-preferences-group reveal-modal" id="dashboard-preferences" data-reveal>
  <div class="reveal-modal__title"><i class="icon-cog"></i> Preferences</div>
  <div class="reveal-modal__content">
    <%= spinner.html_safe %>
    <%= form_for(@dashboard) do |f| %>
    <div class="field">
      <%= f.text_field :name, :class => 'dashboard-preference-text' %>
    </div>
    <div class="field field--extra-margin">
      <label>Shareable url:</label>
      <a href="<%= view_dashboards_path :token => @dashboard.token %>" target="_blank">
        <%= @dashboard.token %>
      </a>
    </div>
    <div class="dashboard-preferences-action">
      <button class="button secondary cancel-dashboard-action">
        <i class="icon-back"></i> Cancel
      </button>
      <button type="submit" class="button primary save-dashboard-action">
        <i class="icon-save"></i> Save
      </button>
    </div>
    <% end %>
    <a class="close-reveal-modal">&#215;</a>
  </div>
</div>

app/views/dashboards/_widgets_modal.html.erb
<div class="widgets-selector-group reveal-modal" id="widgets-selector" data-url="<%= dashboard_add_widget_path({ :dashboard_id => @dashboard.id }) %>" data-reveal>
  <div class="reveal-modal__title">
    <a href="<%= widgets_path %>"><i class="icon-line-graph"></i> Widgets</a>
  </div>
  <div class="reveal-modal__content">
    <div class="widgets-selector-items">
      <% @widgets.each do |widget| %>
        <div
          class="widgets-selector__item"
          data-item
          data-row="<%= widget.row %>"
          data-col="<%= widget.column %>"
          data-url="<%= widget_path widget %>"
          data-id="<%= widget.id %>"
          data-remove-url="<%= dashboard_remove_widget_path({ :dashboard_id => @dashboard.id }) %>"
        >
          <i class="widgets-selector-icon icon-line-graph"></i>
          <%= widget.name %>
          <a
            href="<%= edit_widget_path(widget, :redirect => request.fullpath) %>"
            title="edit this data"
            class="widgets-selector__edit"
          >
            <i class="icon-pencil" data-edit></i>
          </a>
          <%= widget_sandbox.html_safe %>
        </div>
      <% end %>
    </div>

    <div class="widgets-selector__actions">
      <a href="<%= new_widget_path(:redirect => request.fullpath) %>" class="button small">
        <i class="icon-plus"></i>new widget
      </a>
    </div>
  </div>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/dashboards/edit.html.erb
<% content_for :tools do %>
<ul class="right dashboard-tools">
  <li class="divider"></li>
  <li>
    <a href="<%= dashboard_new_widget_path({ dashboard_id: @dashboard.id }) %>" title="add widgets">
      <i class="icon-line-graph dashboard-tools-icon"></i> Add widget
    </a>
  </li>
  <li class="divider"></li>
  <li>
    <a href="#" data-reveal-id="dashboard-preferences" title="add widgets">
      <i class="icon-cog dashboard-tools-icon" title="preferences"></i> Dashboard
    </a>
  </li>
</ul>
<% end %>
<div class="dashboard-menu-group">
  <div class="monitor item">
    <a href="#" title="full screen" class="monitor-fullscreen">
      <i class="icon-monitor dashboard-menu-icon" title="full screen"></i>
    </a>
  </div>
</div>
<div class="dashboard-edit-form-group">
  <div
    class="dashboard gridster"
    data-dimensions="<%= Settings.gridster.dimensions %>"
    data-max-size="<%= Settings.gridster.max_size %>"
    data-update-url="<%= dashboard_update_widgets_path({ :dashboard_id => @dashboard.id }) %>"
    style="width: <%= dashboard_settings.width %>px"
    >
      <ul class="gridster-widgets">
      <% @dashboard_widgets.each do |dw| %>
        <li
          data-col="<%= dw.col %>"
          data-row="<%= dw.row %>"
          data-sizex="<%= dw.size_x %>"
          data-sizey="<%= dw.size_y %>"
          data-url="<%= widget_dashboards_path(:token => @dashboard.token, :dashboard_widget_id => dw.id) %>"
          data-remove-url="<%= dashboard_remove_widget_path({ :dashboard_id => @dashboard.id }) %>"
          data-id="<%= dw.id %>"
        >
          <%= widget_sandbox('', '', dw.widget_id).html_safe %>
          <%= widget_modifier(:remove => true).html_safe %>
        </li>
      <% end %>
      </ul>
  </div>
</div>
<%= render 'widgets_modal' %>
<%= render 'preferences_modal' %>

app/views/dashboards/index.html.erb
<div class="row">
  <div class="large-2 columns">
  </div>
  <div class="large-8 columns large-centered">
    <h1>Dashboards</h1>

    <table class="table--common">
      <thead>
        <tr>
          <th>Name</th>
          <th>Scale</th>
          <th>Is public</th>
          <th>Created by</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
    <% @dashboards.each do |dashboard| %>
        <tr>
          <td>
            <a href="<%= edit_dashboard_path(dashboard) %>"><%= dashboard.name %>
            </a>
          </td>
          <td><%= dashboard.scale %></td>
          <td><%= dashboard.is_public %></td>
          <td><%= dashboard.user.username %></td>
          <td class="action-cell">
            <a href="<%= edit_dashboard_path(dashboard) %>" class="action" title="edit this dashboard"><i class="icon-pencil"></i></a>
          </td>
          <td class="action-cell">
            <a href="<%= dashboard_path(dashboard) %>" class="action" data-confirm="Are you sure?" data-method="delete" title="delete this dashboard">
              <i class="icon-cross"></i>
            </a>
          </td>
        </tr>
    <% end %>
      </tbody>
    </table>

    <br />

    <a href="<%= new_dashboard_path %>" class="button small"><i class="icon-plus"></i>New dashboard</a>
  </div>
  <div class="large-2 columns">
  </div>
</div>

app/views/dashboards/new_widget.html.erb
<% content_for :tools do %>
<ul class="right dashboard-tools">
  <li class="divider"></li>
  <li>
    <a href="<%= edit_dashboard_path(@dashboard) %>" title="add widgets">
      <i class="icon-back dashboard-tools-icon"></i> Back to dashboard
    </a>
  </li>
</ul>
<% end %>

<div class="row widget-selector-group">
  <div class="small-3 columns">
    <div class="widgets-selector__list" data-dashboard-widgets>
      <% @widgets.each do |widget| %>
          <div
              class="widgets-selector__list__item"
              data-widget-item
              data-id="<%= widget.id %>"
              data-meta="<%= widget.meta %>"
              data-html="<%= widget.html %>"
              data-css="<%= widget.css %>"
              data-js="<%= widget.js %>"
              data-column="<%= widget.column %>"
              data-row="<%= widget.row %>"
              data-data=""
          >
              <%= widget.name %>
          </div>
      <% end %>
    </div>
  </div>
  <div class="small-3 columns">
    <div class="content" data-builder>
      <% if @widgets.length %>
        <%= form_tag dashboard_add_widget_path, {
          :class => 'widget-builder-group',
          'data-widget-builder' => '1',
          'data-meta' => ''
        } do %>
          <%= hidden_field_tag 'data', '', { "data-value" => true } %>
          <%= render '/widgets/builder' %>
          <button class="button small secondary" data-preview-btn>Preview</button>
          <button class="button small primary" data-add-btn>Add</button>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="small-6 columns">
    <%= render '/widgets/previewer' %>
  </div>
</div>

app/views/dashboards/view.html.erb
<% content_for :tools do %>
<ul class="right dashboard-tools">
  <li class="divider"></li>
  <li>
    <% if user_signed_in? %>
      <a href="<%= edit_dashboard_path @dashboard %>">Edit this dashboard</a>
    <% else %>
      <a href="#"><%= @dashboard.name %></a>
    <% end %>
  </li>
</ul>
<% end %>
<div
  class="dashboard gridster"
  data-dimensions="<%= Settings.gridster.dimensions %>"
  data-max-size="<%= Settings.gridster.max_size %>"
  style="width: <%= dashboard_settings.width %>px"
  >
    <ul class="gridster-widgets">
    <% @dashboard_widgets.each do |dw| %>
      <li
:id         data-col="<%= dw.col %>"
        data-row="<%= dw.row %>"
        data-sizex="<%= dw.size_x %>"
        data-sizey="<%= dw.size_y %>"
        data-url="<%= widget_dashboards_path(:token => @dashboard.token, :dashboard_widget_id => dw.id) %>"
        data-id="<%= dw.id %>">
        <%= widget_sandbox('', '', dw.widget_id, 'interactive').html_safe %>
      </li>
    <% end %>
    </ul>
</div>

app/views/dashboards/widget.html.erb
<%= render '/widgets/widget', {
  :css => @widget.parsed_css,
  :html => @widget.parsed_html,
  :js => @widget.parsed_js
} %>