config/routes.rb
Observer::Application.routes.draw do
  resources :connections

  resources :dashboards do
    match 'update-widgets' => 'dashboards#update_widgets', :as => :update_widgets, :constraints => {:format => /json/}
    match 'add-widget' => 'dashboards#add_widget', :as => :add_widget, :via => :post
    match 'new-widget' => 'dashboards#new_widget', :as => :new_widget
    match 'remove-widget' => 'dashboards#remove_widget', :as => :remove_widget, :constraints => {:format => /json/}

    collection do
      match 'view/:token' => 'dashboards#view', :as => :view
      match 'view/:token/widgets/:dashboard_widget_id' => 'dashboards#widget', :as => :widget
    end
  end

  resources :widgets do
    collection do
      match 'tag/:tag' => 'widgets#show_tag', :as => :show_tag
      match 'preview', :as => :preview
      match 'copy/:id' => 'widgets#copy', :as => :copy
    end
  end

  resources :queries do
    collection do
      post 'run'
      match 'data/:token' => 'queries#data', :constraints => {:format => /(html)/}, :as => :data
      match 'copy/:id' => 'queries#copy', :as => :copy
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  match 'ajax-proxy' => 'website#ajax'

  root :to => 'website#index'

end

app/models/query.rb
class Query < ActiveRecord::Base
  attr_accessible :name, :token, :value, :connection_id, :user_id
  before_create :generate_token
  belongs_to :user
  belongs_to :db_connection, :class_name => 'Connection', :foreign_key =>
"connection_id"
  validates :name, :presence => true

  def value_as_query(vars = {})
    LiquidTemplate.for_query.parse(self.value).render vars
  end

  protected

  def generate_token
    self.token = loop do
      random_secret = SecureRandom.urlsafe_base64(6, false).downcase
      break random_secret unless self.class.exists?(token: random_secret)
    end
  end
end

app/controllers/queries_controller.rb
require 'db_client'

class QueriesController < ApplicationController
  include QueriesHelper

  before_filter :authenticate_user!, :except => [:data]
  # GET /queries
  # GET /queries.json
  def index
    @queries = Query.all(:include => :user)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @queries }
    end
  end

  # GET /queries/new
  # GET /queries/new.json
  def new
    @query = Query.new
    @query.user = current_user
    @query.name = 'untitled'
    @query.value = ''
    @query.save

    # print @query.errors
    redirect_to(edit_query_path(@query, :redirect => params[:redirect]))
  end

  # GET /queries/1/edit
  def edit
    @redirect = param(:redirect, queries_path)

    @query = Query.find(params[:id])
    @connections = Connection.all
  end

  def copy
    @query = Query.find(params[:id])
    attributes = @query.attributes
    attributes.delete('id')
    attributes.delete('created_at')
    attributes.delete('updated_at')
    attributes.delete('token')

    query = Query.new
    query.attributes = attributes
    query.name = "#{query.name} (1)"
    query.save

    redirect_to(
      edit_query_path(query.id, :redirect => params[:redirect])
    )
  end

  # POST /queries/run
  def run
    if (!request.xhr?)
      raise ActionController::RoutingError.new('Not Found')
    end

    connection = Connection.find params[:connection_id]

    client = DBClient.create connection

    queryTemplate = LiquidTemplate.for_query.parse(params[:value])
    @sql = queryTemplate.render

    @result = client.query @sql
    @queryError = client.last_query_error
    render :partial => 'result'
  end

  # GET /queries/data/:token
  def data
    @query = Query.find_by_token!(params[:token])

    if @query.nil?
      raise ActionController::RoutingError.new('Not Found')
    end

    client = DBClient.create @query.db_connection
    query = @query.value_as_query(params)

    logger.debug "Executing query: #{query}"

    @result = client.query query
    client.close

    if @result
      data = {
        :result => @result,
        :fields => @result.fields
      }
    else
      data = {
        :error => client.last_query_error.to_s
      }
    end

    respond_to do |format|
      format.html { render json: data, status: :created }
    end
  end

  # PUT /queries/1
  # PUT /queries/1.json
  def update
    @query = Query.find(params[:id])

    if params[:query][:connection_id].present?
      connection = Connection.find(params[:query][:connection_id])
      @query.db_connection = connection
    end

    respond_to do |format|
      if @query.update_attributes(params[:query])
        format.json { head :no_content }
      else
        flash[:errors] = @query.errors
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /queries/1
  # DELETE /queries/1.json
  def destroy
    @query = Query.find(params[:id])
    @query.destroy

    respond_to do |format|
      format.html { redirect_to queries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/queries_helper.rb
module QueriesHelper
  def handle_query_post(request)
    if (!request.params[:value].nil?)
      query = request.params[:value]
      client = Mysql2::Client.new(
        :host => "localhost",
        :username => "root"
      )

      return client.query(query)
    end
  end
  end

app/views/queries/_result.html.erb
<% if @queryError %>
  <div data-alert class="alert-box alert secondary">
    <p><%= @queryError %></p>
    <code><%= @sql %></code>
  </div>
<% else %>
 <table class="result-table table--common">
    <thead>
      <tr>
        <% @result.fields.each do |field| %>
          <th><%= field %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @result.each(:as => :array) do |row| %>
        <tr>
          <% row.each do |col| %>
            <td><%= col %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/queries/edit.html.erb
<% content_for :tools do %>
<ul class="right dashboard-tools">
  <li class="divider"></li>
  <li>
    <a href="<%= copy_queries_path @query, :redirect => @rediect %>" data-confirm="Save this as a new query?" class="query-done">
      <i class="icon-docs dashboard-tools-icon" title="done"></i> Save as
    </a>
  </li>
  <li class="divider"></li>
  <li>
    <a href="<%= @redirect %>" class="query-done">
      <i class="icon-forward dashboard-tools-icon" title="done"></i> Done
    </a>
  </li>
</ul>
<% end %>
<div class="row query-edit-form-group">
  <div class="columns large-12">
    <div
      class="query-name editable-name"
      data-url="<%= query_path %>"
      data-name="query[name]"
      contenteditable="true"
    >
      <%= @query.name %>
    </div>
    <%= form_for(
        @query,
        :html => {
          :class => 'custom query-form',
          'data-query-form' => true,
          'data-target' => '[data-result-content]'
        }
      ) do |f| %>
      <%= render '/form_errors' %>
      <div class="query-editor-group field">
        <%= f.hidden_field :value %>
        <%=
        render '/editor',
          :mode => 'sql',
          :url => query_path,
          :prefix => 'query',
          :bind => '#query_value'
        %>
        <div class="row query-form-actions-group">
          <div class="columns large-2 right query-form__actions field">
            <a
              href="#"
              class="button query-form__actions__run secondary"
              data-url="<%= run_queries_path %>"
              data-run-btn
            ><i class="icon-triangle-right"></i>Run</a>
          </div>
          <div class='columns large-6'>
          </div>
          <div class='columns large-3'>
            <%= select(
              :query,
              :connection_id,
              @connections.collect { |c|
                [connection_name(c), c.id]
              },
              :class => 'medium'
            ) %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="query-form__actions__result" data-result-content>
    </div>
  </div>
</div>

app/views/queries/index.html.erb
<div class="row">
  <div class="large-2 columns">
  </div>
  <div class="large-8 columns large-centered">
    <h1>Data source</h1>
    <table class="table--common">
      <thead>
        <tr>
          <th>Name</th>
          <th>Token</th>
          <th>created by</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @queries.each do |query| %>
        <tr>
          <td>
            <a href="<%= edit_query_path(query) %>">
              <%= query.name %>
            </a>
          </td>
          <td>
          <% if query.db_connection.present? %>
            <%= link_to query.token, data_queries_path({:token => query.token}), :target => '_blank' %>
          <% end %>
          </td>
          <td><%= query.user.username %></td>
          <td class="action-cell">
              <a href="<%= edit_query_path(query) %>" class="action"><i class="icon-pencil"></i></a>
          </td>
          <td class="action-cell">
            <a href="<%= query_path(query) %>" class="action" data-confirm="Are you sure?" data-method="delete">
              <i class="icon-cross"></i>
            </a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br />

    <a href="<%= new_query_path %>" class="button small"><i class="icon-plus"></i>New query</a>
  </div>
  <div class="large-2 columns">
  </div>
</div>