config/routes.rb
Observer::Application.routes.draw do
  resources :connections

  resources :dashboards do
    match 'update-widgets' => 'dashboards#update_widgets', :as => :update_widgets, :constraints => {:format => /json/}
    match 'add-widget' => 'dashboards#add_widget', :as => :add_widget, :via => :post
    match 'new-widget' => 'dashboards#new_widget', :as => :new_widget
    match 'remove-widget' => 'dashboards#remove_widget', :as => :remove_widget, :constraints => {:format => /json/}

    collection do
      match 'view/:token' => 'dashboards#view', :as => :view
      match 'view/:token/widgets/:dashboard_widget_id' => 'dashboards#widget', :as => :widget
    end
  end

  resources :widgets do
    collection do
      match 'tag/:tag' => 'widgets#show_tag', :as => :show_tag
      match 'preview', :as => :preview
      match 'copy/:id' => 'widgets#copy', :as => :copy
    end
  end

  resources :queries do
    collection do
      post 'run'
      match 'data/:token' => 'queries#data', :constraints => {:format => /(html)/}, :as => :data
      match 'copy/:id' => 'queries#copy', :as => :copy
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  match 'ajax-proxy' => 'website#ajax'

  root :to => 'website#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Observer" %></title>

    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  	<%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/2.2.0/es5-sham.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/2.2.0/es5-shim.min.js" type="text/javascript"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js" type="text/javascript"></script>

    <script src="/assets/javascripts/lib/flight.js" type="text/javascript"></script>
    <%= csrf_meta_tags %>
  </head>

  <body
    id="app_body"
    class="<%= "#{controller.controller_name} #{controller.action_name}" %>"
    data-triggerjs="<%= "#{controller.action_name}.#{controller.controller_name}" %>"
  >
      <nav class="top-bar userbar" data-topbar>
        <section class="top-bar-section components-menu">
          <ul class="left title-area">
            <li class="<% if user_signed_in? %>has-dropdown<% end %> name"><a href="/" class="brand-title">Observer</a>
            <% if user_signed_in? %>
            <ul class="dropdown">
              <li>
                <a
                  href="<%= connections_path %>"
                  >
                  <i class="icon-cloud"></i>
                  Connections</a>
              </li>
              <li>
                <a
                  href="<%= queries_path %>"
                  ><i class="icon-database"></i> Data source</a>
              </li>
              <li>
                <a
                  href="<%= widgets_path %>"
                  ><i class="icon-line-graph"></i> Widgets</a>
              </li>
              <li>
                <a
                  href="<%= dashboards_path %>"
                  ><i class="icon-layout"></i>Dashboards</a>
              </li>
            </ul>
            <% end %>
            </li>
            <li>
              <div class="global-spinner">
                <%= spinner.html_safe %>
              </div>
            </li>
          </ul>
          <!-- Right Nav Section -->
          <ul class="right">
              <li class="divider"></li>
              <% if !user_signed_in? %>
              <li>
                <a class="login action" href="<%= new_user_session_path %>">
                  <i class="icon-login"></i> Log in
                </a>
              </li>
              <% else %>
              <li class="has-dropdown">
                <a href="#"><i class="icon-user"></i> <%= current_user.username %></a>
                <ul class="dropdown">
                  <li>
                    <a href="<%= edit_user_registration_path %>">
                      <i class="icon-pencil"></i> Update account
                    </a>
                    <a href="<%= destroy_user_session_path %>" data-method="delete" class="logout action" title="logout">
                      <i class="icon-logout"></i> Log out
                    </a>
                  </li>
                </ul>
              </li>
              <% end %>
          </ul>
          <%= yield :tools %>
        </section>
      </nav>
    <div class="layout-container">
        <% if !flash[:notice].nil? %>
        <div data-alert class="alert-box success">
          <%= flash[:notice] %>
          <a href="#" class="close">&times;</a>
        </div>
        <% end %>
        <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= yield :javascript %>
    <%= render '/modal' %>
    <div id="zclip" data-swf="<%= asset_path('ZeroClipboard.swf') %>"></div>
  </body>
</html>

app/views/layouts/basic.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Observer" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/2.2.0/es5-sham.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/2.2.0/es5-shim.min.js" type="text/javascript"></script>
    <script src="//codeorigin.jquery.com/jquery-2.0.3.min.js" type="text/javascript"></script>
    <script src="/assets/javascripts/lib/flight.js" type="text/javascript"></script>
    <%= csrf_meta_tags %>
  </head>

  <body
    id="app_body"
    class="<%= "#{controller.controller_name} #{controller.action_name}" %>"
    data-triggerjs="<%= "#{controller.action_name}.#{controller.controller_name}" %>"
  >
    <%= yield %>

    <%= javascript_include_tag 'basic' %>
    <%= yield :javascript %>
  </body>
</html>